# -*- coding: utf-8 -*-
"""Crawling twitter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oggJ0ykl-lnlll6OKswY1DR2Hx5LEeLq
"""

# Import required Python package
!pip install pandas

# Install Node.js (karena tweet-harvest di built menggunakan Node.js)
!sudo apt-get update
!sudo apt-get install -y ca-certificates curl gnupg
!sudo mkdir -p /etc/apt/keyrings

!curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o/etc/apt/keyrings/nodesource.gpg

!NODE_MAJOR=20 && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list

!sudo apt-get update
!sudo apt-get install nodejs -y

!node -v

# Crawl Data

filename = 'Kurs_Rupiah.csv'
search_keyword = 'Kurs Rupiah 2024 until:2024-04-26 since:2024-03-26 lang:id'
limit = 50

!npx --yes tweet-harvest@2.6.0 -o "{filename}" -s "{search_keyword}" -l {limit} --token ""

import pandas as pd

# Specify the path to your CSV file
file_path = f"tweets-data/{filename}"

# Read the CSV file into a pandas DataFrame
df = pd.read_csv(file_path, delimiter=",")

# Display the DataFrame
display(df)